version: '3.8'

services:
  postgres:
    build:
      context: ./employee_service/db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    build:
      context: ./employee_service/app
    command: sh -c "sleep 5 && python app.py"
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - ./employee_service/app:/app
    env_file:
      - .env
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
    ports:
      - "2181:2181"
  

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer:
    build: 
      context: ./producer_service
    depends_on:
      - postgres
      - kafka
    environment:
      - PYTHONUNBUFFERED=1
    command: python /app/producer_service.py
    env_file:
      - .env


volumes:
  postgres_data:
