version: '3.8'

services:
  postgres:
    build:
      context: ./employee_service/db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    build:
      context: ./employee_service/app
    command: sh -c "sleep 5 && python app.py"
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - ./employee_service/app:/app
    env_file:
      - .env

volumes:
  postgres_data:
